title: Ludmarus'
email: ludmarus@ludmarus.com
description: Ludmarus' personal website
github_username: Ludmarus

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Ludmarus"