title: Ludmarus'
email: ludmarus@ludmarus.com
description: Ludmarus' personal website + blog
twitter_username: Ludmarus
github_username: Ludmarus

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Ludmarus"