title: Ludmarus'
description: Página personal
twitter_username: Ludmarus
github_username: Ludmarus

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Ludmarus"